spring:
  application:
    name: accounts
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: postgres
    password: Mac@2020
server:
  error:
    include-stacktrace: on_param
contact:
  title: Ezeebank accounts contact support
  details:
    name: Ashu
    email: ashwu@gmail.com
  phoneNos:
    -674476633
    -664646465

